version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  batch-processing:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/docker
      SPRING_DATASOURCE_USERNAME: docker
      SPRING_DATASOURCE_PASSWORD: docker
      SERVER_PORT: 9090
    command: ["/wait-for-postgres.sh", "postgres", "java", "-jar", "batch-processing.jar"]
    volumes:
      - ./src/main/resources/output:/app/src/main/resources/output

volumes:
  postgres_data:
